name: CI
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.14.x
    - name: Generate files
      run: go generate -v -x
    - name: go fmt
      run: go fmt
    - name: check for any changes
      run: go run ./scripts/validate_ci/main.go
    - name: Test
      run: go test ./...
